# Generated by Django 6.0 on 2025-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='Menüde Gösterilsin mi?'),
        ),
    ]
