# Generated by Django 6.0 on 2025-12-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_category_show_in_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Slogan (Başlık)')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Başlık')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='Slider Görseli')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama (Küçükten büyüğe)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider Yönetimi',
                'ordering': ['order'],
            },
        ),
    ]
