# Generated by Django 6.0 on 2025-12-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Yazı Başlığı')),
                ('content', models.TextField(verbose_name='Yazı İçeriği')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Kapak Görseli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yönetimi',
                'ordering': ['-created_at'],
            },
        ),
    ]
