# Generated by Django 6.0 on 2025-12-24 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Oda Adı (Örn: Mutfak)')),
                ('image_before', models.ImageField(upload_to='transformations/', verbose_name='Öncesi (Eski Hali)')),
                ('image_after', models.ImageField(upload_to='transformations/', verbose_name='Sonrası (Yeni Hali)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='portfolio.project')),
            ],
        ),
    ]
