# Generated by Django 6.0 on 2025-12-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_transformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Hizmet Başlığı')),
                ('description', models.TextField(verbose_name='Kısa Açıklama')),
                ('icon', models.ImageField(upload_to='services/', verbose_name='İkon (Küçük Resim)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['order'],
            },
        ),
    ]
