# Generated by Django 6.0 on 2026-01-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta Adresi')),
                ('address', models.TextField(verbose_name='Adres')),
                ('map_link', models.TextField(blank=True, null=True, verbose_name='Google Maps Embed Linki (iframe içindeki src)')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Linki')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn Linki')),
                ('about_title', models.CharField(default='Biz Kimiz?', max_length=200, verbose_name='Hakkımızda Başlık')),
                ('about_description', models.TextField(verbose_name='Hakkımızda Metni')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Hakkımızda Görseli')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
